### ISSUE TITLE
error in use"python run_tracker.py -d DragonBaby" and "python run_tracker.py -f DragonBaby"

### ISSUE THREAD

**Issue by wassonxu** [HyeonseobNam/py-MDNet#1]
wasson@wasson-MS-7971:~/yujia/py-MDNet-master/tracking$ python run_tracker.py -d DragonBaby
usage: run_tracker.py [-h] [-s SEQ] [-j JSON] [-f] [-d]
run_tracker.py: error: unrecognized arguments: DragonBaby

**Comment by wassonxu** [comment]
how to generate the corresponding video of DragonBaby?  
Thank you very much~

**Comment by HyeonseobNam** [comment]
@wassonxu 
Try ```python run_tracker.py -s DragonBaby -d -f``` :)

**Comment by wassonxu** [comment]
It works.  Thank you very much :)

**Comment by hehewa** [comment]
After I run the command:
```
python run_tracker.py -s DragonBaby -d -f
```
I have the wrong result:
```
Traceback (most recent call last):
  File "run_tracker.py", line 25, in <module>
    torch.cuda.manual_seed(789)
  File "/home/xx/anaconda2/lib/python2.7/site-packages/torch/cuda/random.py", line 27, in manual_seed
    _lazy_init()
  File "/home/xx/anaconda2/lib/python2.7/site-packages/torch/cuda/__init__.py", line 84, in _lazy_init
    _check_driver()
  File "/home/xx/anaconda2/lib/python2.7/site-packages/torch/cuda/__init__.py", line 51, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

```

Please Help!Thank you very much!!

**Comment by qianliangchang** [comment]
excuse me,please forgive that I'm small.
why I got the wrong result? Thanks for your help!
................
`[root@localhost tracking]# python run_tracker.py -s DragonBaby -d -f
Traceback (most recent call last):
  File "run_tracker.py", line 8, in <module>
    import matplotlib.pyplot as plt
  File "/usr/lib64/python2.7/site-packages/matplotlib/pyplot.py", line 97, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/__init__.py", line 25, in pylab_setup
    globals(),locals(),[backend_name])
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_gtkagg.py", line 10, in <module>
    from matplotlib.backends.backend_gtk import gtk, FigureManagerGTK, FigureCanvasGTK,\
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_gtk.py", line 13, in <module>
    import gtk; gdk = gtk.gdk
  File "/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py", line 64, in <module>
    _init()
  File "/usr/lib64/python2.7/site-packages/gtk-2.0/gtk/__init__.py", line 52, in _init
    _gtk.init_check()
RuntimeError: could not open display`

**Comment by ahkarami** [comment]
Dear @HyeonseobNam,
After I run the command:
`python run_tracker.py -s DragonBaby -d -f`
the below error has occurred:
```
Traceback (most recent call last):
  File "run_tracker.py", line 329, in <module>
    result, result_bb, fps = run_mdnet(img_list, init_bbox, gt=gt, savefig_dir=savefig_dir, display=display)
  File "run_tracker.py", line 129, in run_mdnet
    model = MDNet(opts['model_path'])
  File "../modules/model.py", line 78, in __init__
    self.build_param_dict()
  File "../modules/model.py", line 83, in build_param_dict
    append_params(self.params, module, name)
  File "../modules/model.py", line 13, in append_params
    for k,p in child._parameters.iteritems():
AttributeError: 'collections.OrderedDict' object has no attribute 'iteritems'
```

Would you please kindly help me to address this problem?

**Comment by Pratik124** [comment]
dear @ahkarami  I have got the same error 
AttributeError: 'collections.OrderedDict' object has no attribute 'iteritems'

can you please explain what was the issue?

**Comment by nazi96** [comment]
> It works. Thank you very much :)

hello
I have problem in running the code. I am realy confused. I think you run the code corectly. would you please help me to run the model??

**Comment by nazi96** [comment]
> It works. Thank you very much :)
@wassonxu 
hello
I have problem in running the code. I am realy confused. I think you run the code corectly. would you please help me to run the model??
