### ISSUE TITLE
RuntimeError: CUDNN_STATUS_NOT_SUPPORTED.  When run the train_mdnet.py 

### ISSUE THREAD

**Issue by flyingmoth** [HyeonseobNam/py-MDNet#2]
Traceback (most recent call last):
  File "/home/kai_xu/PycharmProjects/py-MDNet/pretrain/train_mdnet.py", line 100, in <module>
    train_mdnet()
  File "/home/kai_xu/PycharmProjects/py-MDNet/pretrain/train_mdnet.py", line 71, in train_mdnet
    pos_score = model(pos_regions, k)
  File "/home/kai_xu/anaconda3/envs/pytorch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "../modules/model.py", line 111, in forward
    x = module(x)
  File "/home/kai_xu/anaconda3/envs/pytorch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kai_xu/anaconda3/envs/pytorch/lib/python2.7/site-packages/torch/nn/modules/container.py", line 64, in forward
    input = module(input)
  File "/home/kai_xu/anaconda3/envs/pytorch/lib/python2.7/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kai_xu/anaconda3/envs/pytorch/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 237, in forward
    self.padding, self.dilation, self.groups)
  File "/home/kai_xu/anaconda3/envs/pytorch/lib/python2.7/site-packages/torch/nn/functional.py", line 40, in conv2d
    return f(input, weight, bias)
RuntimeError: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.

**Comment by flyingmoth** [comment]
I have solved this problem.  I used the wrong 'imagenet-vgg-m.mat' .
