### ISSUE TITLE
Running the program has encountered a problem

### ISSUE THREAD

**Issue by donggc** [HyeonseobNam/py-MDNet#27]
I use 'python run_tracker.py  -s DragonBaby -d -f',but  it is wrong.
**This is the information printed by the terminal：**
Traceback (most recent call last):
  File "run_tracker.py", line 330, in <module>
    result, result_bb, fps = run_mdnet(img_list, init_bbox, gt=gt, savefig_dir=savefig_dir, display=display)
  File "run_tracker.py", line 147, in run_mdnet
    bbreg_feats = forward_samples(model, image, bbreg_examples)
  File "run_tracker.py", line 35, in forward_samples
    feat = model(regions, out_layer=out_layer)
  File "/home/casic/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/projects/ObjectTracking/single/py-MDNet-master/model.py", line 110, in forward
    x = module(x)
  File "/home/casic/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/cs/.local/lib/python2.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/cs/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/projects/ObjectTracking/single/py-MDNet-master/model.py", line 40, in forward
    torch.cat((pad,pad,pad,pad,x_sq),2)),1)
RuntimeError: CUDA out of memory. Tried to allocate 1.24 GiB (GPU 0; 3.95 GiB total capacity; 1.77 GiB already allocated; 1.15 GiB free; 242.18 MiB cached)

**Comment by universefall** [comment]
I also have same problem when run 'python run_tracker.py -s DragonBaby -d -f', and print following information:
`Traceback (most recent call last):
  File "run_tracker.py", line 326, in <module>
    img_list, init_bbox, gt, savefig_dir, display, result_path = gen_config(args)
  File "/Users/bill/Documents/py-MDNet-master/tracking/gen_config.py", line 18, in gen_config
    img_list = os.listdir(img_dir)
OSError: [Errno 2] No such file or directory: '../dataset/OTB/DragonBaby-f/img'
(pyenv_1) billtekiMacBook-Air:tracking bill$ python run_tracker.py -s DragonBaby -f
../modules/model.py:144: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  pos_loss = -F.log_softmax(pos_score)[:,1]
../modules/model.py:145: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  neg_loss = -F.log_softmax(neg_score)[:,0]
run_tracker.py:113: UserWarning: torch.nn.utils.clip_grad_norm is now deprecated in favor of torch.nn.utils.clip_grad_norm_.
  torch.nn.utils.clip_grad_norm(model.parameters(), opts['grad_clip'])
Traceback (most recent call last):
  File "run_tracker.py", line 329, in <module>
    result, result_bb, fps = run_mdnet(img_list, init_bbox, gt=gt, savefig_dir=savefig_dir, display=display)
  File "run_tracker.py", line 190, in run_mdnet
    im = ax.imshow(image, aspect='normal')
  File "/Users/bill/anaconda3/envs/pyenv_1/lib/python2.7/site-packages/matplotlib/__init__.py", line 1867, in inner
    return func(ax, *args, **kwargs)
  File "/Users/bill/anaconda3/envs/pyenv_1/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 5496, in imshow
    self.set_aspect(aspect)
  File "/Users/bill/anaconda3/envs/pyenv_1/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 1373, in set_aspect
    aspect = float(aspect)  # raise ValueError if necessary
ValueError: could not convert string to float: normal`
It doesnt show any images and save results.

**Comment by HyeonseobNam** [comment]
Hi, @donggc You need ~3GB free GPU memory to run this software.
