### ISSUE TITLE
Problem during tracking

### ISSUE THREAD

**Issue by yuz79** [HyeonseobNam/py-MDNet#48]
Hello, I encountered a problem when running "python tracking/run_tracker.py -s DragonBaby", the error below shows when I run the command:
Traceback (most recent call last):
  File "tracking/run_tracker.py", line 325, in <module>
    result, result_bb, fps = run_mdnet(img_list, init_bbox, gt=gt, savefig_dir=savefig_dir, display=display)
  File "tracking/run_tracker.py", line 150, in run_mdnet
    train(model, criterion, init_optimizer, pos_feats, neg_feats, opts['maxiter_init'])
  File "tracking/run_tracker.py", line 83, in train
    score = model(batch_neg_feats[start:end], in_layer=in_layer)
  File "C:\MIMIA\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File ".\modules\model.py", line 120, in forward
    x = module(x)
  File "C:\MIMIA\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\MIMIA\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\container.py", line 100, in forward
    input = module(input)
  File "C:\MIMIA\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\MIMIA\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\modules\linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "C:\MIMIA\Anaconda3\envs\pytorch\lib\site-packages\torch\nn\functional.py", line 1610, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)

Please help me. Thanks!!!!

**Comment by xwr96** [comment]
I think is the CUDA problem！no the code
