### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by rnunziata** [HyeonseobNam/py-MDNet#7]
about the 44 frame processed  ... run out of memory....running 
python run_tracker.py -s DragonBaby -d 
Any idea why this is happening?

```
    return torch.cat(inputs, self.dim)
RuntimeError: cuda runtime error (2) : out of memory at /b/wheel/pytorch-src/torch/lib/THC/generic/THCStorage.cu:66

```

**Comment by Adeel-Abdullah** [comment]
I've been getting the exact same error, I was using the nvidia gtx 960M of my laptop which has 2gb of memory, looks like 2gb is simply not enough for this. It'd be nice to know how much gpu memory we do require for running MDNet

**Comment by ahkarami** [comment]
I have also tested the code via 4 Gb GPU, but I got the below error:
```
File "../modules/model.py", line 40, in forward
    torch.cat((pad,pad,pad,pad,x_sq),2)),1)
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1512386481460/work/torch/lib/THC/generic/THCStorage.cu:58
```

**Comment by ciokan** [comment]
```
python run_tracker.py -s DragonBaby -d -f
THCudaCheck FAIL file=/pytorch/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "run_tracker.py", line 329, in <module>
    result, result_bb, fps = run_mdnet(img_list, init_bbox, gt=gt, savefig_dir=savefig_dir, display=display)
  File "run_tracker.py", line 146, in run_mdnet
    bbreg_feats = forward_samples(model, image, bbreg_examples)
  File "run_tracker.py", line 33, in forward_samples
    regions = regions.cuda()
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/generic/THCStorage.cu:58
```

Titan X 12GB - the vcard goes to 20% on memory then this error pops out. Any ideas?
